/**
 * Demo market data used when no wallet/API is configured, so the full flow
 * works out of the box. Shapes match the SDK's normalized MarketState.
 */

import type { MarketState } from "@vibequant/sdk";

const now = Date.now();
const inDays = (d: number) => now + d * 86_400_000;

export const DEMO_MARKETS: MarketState[] = [
  {
    id: "demo-trump-finish-term",
    marketAppId: 900001,
    title: "Will Donald Trump complete his current presidential term?",
    slug: "trump-complete-term",
    categories: ["Politics", "US"],
    yesAssetId: 1,
    noAssetId: 2,
    yesProbability: 0.86,
    noProbability: 0.14,
    volume: 1_240_000,
    endTime: inDays(900),
    isResolved: false,
    isLive: true,
    feeBasePercent: 0.02,
    source: "api",
    updatedAt: now,
  },
  {
    id: "demo-vp-becomes-president",
    marketAppId: 900002,
    title: "Will the sitting Vice President become President before 2029?",
    slug: "vp-becomes-president-2029",
    categories: ["Politics", "Succession"],
    yesAssetId: 3,
    noAssetId: 4,
    yesProbability: 0.12,
    noProbability: 0.88,
    volume: 410_000,
    endTime: inDays(900),
    isResolved: false,
    isLive: true,
    feeBasePercent: 0.02,
    source: "api",
    updatedAt: now,
  },
  {
    id: "demo-republican-2028",
    marketAppId: 900003,
    title: "Will a Republican win the 2028 US presidential election?",
    slug: "republican-wins-2028",
    categories: ["Politics", "Elections"],
    yesAssetId: 5,
    noAssetId: 6,
    yesProbability: 0.49,
    noProbability: 0.51,
    volume: 2_980_000,
    endTime: inDays(1000),
    isResolved: false,
    isLive: true,
    feeBasePercent: 0.02,
    source: "api",
    updatedAt: now,
  },
  {
    id: "demo-btc-100k",
    marketAppId: 900010,
    title: "Will Bitcoin trade above $150,000 before 2027?",
    slug: "btc-above-150k-2027",
    categories: ["Crypto"],
    yesAssetId: 7,
    noAssetId: 8,
    yesProbability: 0.38,
    noProbability: 0.62,
    volume: 5_120_000,
    endTime: inDays(540),
    isResolved: false,
    isLive: true,
    feeBasePercent: 0.02,
    source: "api",
    updatedAt: now,
  },
  {
    id: "demo-fed-cut",
    marketAppId: 900011,
    title: "Will the Fed cut rates at its next meeting?",
    slug: "fed-cut-next-meeting",
    categories: ["Economy", "Rates"],
    yesAssetId: 9,
    noAssetId: 10,
    yesProbability: 0.64,
    noProbability: 0.36,
    volume: 880_000,
    endTime: inDays(40),
    isResolved: false,
    isLive: true,
    feeBasePercent: 0.02,
    source: "api",
    updatedAt: now,
  },
  {
    id: "demo-lakers-title",
    marketAppId: 900020,
    title: "Will the Lakers win the next NBA Championship?",
    slug: "lakers-nba-title",
    categories: ["Sports", "NBA"],
    yesAssetId: 11,
    noAssetId: 12,
    yesProbability: 0.09,
    noProbability: 0.91,
    volume: 1_010_000,
    endTime: inDays(220),
    isResolved: false,
    isLive: true,
    feeBasePercent: 0.02,
    source: "api",
    updatedAt: now,
  },
];

export const DEMO_WALLET = "DEMOWALLETADDRESSXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
export const DEMO_USDC_BALANCE = 250;
export const DEMO_ALGO_BALANCE = 12.5;
